### PR TITLE
package-lock.json is useless, be gone my friend!

### PR DESCRIPTION
**Pull request by PassTheMayo**

### CODE REVIEW

**Comment by oklookitsAugust** [comment]
pull pull pull pull pull

**Comment by PassTheMayo** [comment]
@funnbot that site is a scam 😉

**Comment by PassTheMayo** [comment]
don't listen to it

**Comment by oklookitsAugust** [comment]
Why the fuck you lying @PassTheMayo

**Comment by oklookitsAugust** [comment]
Why the fuck you lying~

why you always lying~

**Comment by PassTheMayo** [comment]
lol jk still package-lock.json is annoying and no one cares

**Comment by oklookitsAugust** [comment]
I think so too 😃

**Comment by iDerp** [comment]
Yea you be lying
Proof

**Comment by oklookitsAugust** [comment]
why u post the image? 🤔

**Comment by PassTheMayo** [comment]
bruh

**Comment by PassTheMayo** [comment]
lets

**Comment by PassTheMayo** [comment]
spam

**Comment by PassTheMayo** [comment]
the

**Comment by PassTheMayo** [comment]
discord

**Comment by iDerp** [comment]
Because this issue has become a chat thread...
Rip git channel

**Comment by PassTheMayo** [comment]
channel

**Comment by PassTheMayo** [comment]
yea

**Comment by PassTheMayo** [comment]
it

**Comment by PassTheMayo** [comment]
has

**Comment by iDerp** [comment]
My phone is dying rn from all the email notifications. And @PassTheMayo you gonna get beaned. Someone, plz close this thread, kthx.

**Comment by ohlookitsAugust** [comment]
been
blowing
up
since
this
is
a
long
comment
asshole
xd

**Comment by ohlookitsAugust** [comment]
close
close
close
close
close
close
close

**Comment by ohlookitsAugust** [comment]
hehe :3

**Comment by PassTheMayo** [comment]
*refuses to close pr*

**Comment by PassTheMayo** [comment]
lol

**Comment by lepon01** [comment]
Please do not spam GitHub

**Pull request closed without merging**
